apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-portfolio-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-portfolio-app
  template:
    metadata:
      labels:
        app: devops-portfolio-app
    spec:
      containers:
      - name: webapp
        image: devops-portfolio-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
