apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-app-service
spec:
  selector:
    app: devops-portfolio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
